on: 
  push:
    branches:
      - main
name: Publish Website to CPanel
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.PMB_SERVER }}
        username: ${{ secrets.PMB_USERNAME }}
        password: ${{ secrets.PMB_PASSWD }}
